# Example configuration entry
sensor:
  - platform: dht
    model: AM2302
    pin: D4
    temperature:
      name: "waschraum Temperatur"
    humidity:
      name: "waschraum Luftfeuchtigkeit"
    update_interval: 5s


esphome:
  name: waschraum

esp8266:
  board: d1_mini

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  password: !secret ota_pw

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Waschraum Fallback Hotspot"
    password: !secret ap_fallback_pw

captive_portal:

